import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "iba-primary": "#005f6a",
        "iba-on-primary": "#ffffff",
        "iba-primary-container": "#007a87",
        "iba-on-primary-container": "#d5f9ff",
        "iba-secondary": "#006398",
        "iba-on-secondary": "#ffffff",
        "iba-secondary-container": "#5bb8fe",
        "iba-on-secondary-container": "#00476e",
        "iba-tertiary": "#903d00",
        "iba-on-tertiary": "#ffffff",
        "iba-tertiary-container": "#b74f00",
        "iba-on-tertiary-container": "#ffefe9",
        "iba-error": "#ba1a1a",
        "iba-on-error": "#ffffff",
        "iba-error-container": "#ffdad6",
        "iba-on-error-container": "#93000a",
        "iba-background": "#f8f9ff",
        "iba-on-background": "#0b1c30",
        "iba-surface": "#f8f9ff",
        "iba-on-surface": "#0b1c30",
        "iba-surface-variant": "#d3e4fe",
        "iba-on-surface-variant": "#3e494a",
        "iba-outline": "#6e797b",
        "iba-outline-variant": "#bdc8cb",
        "iba-surface-container-lowest": "#ffffff",
        "iba-surface-container-low": "#eff4ff",
        "iba-surface-container": "#e5eeff",
        "iba-surface-container-high": "#dce9ff",
        "iba-surface-container-highest": "#d3e4fe",
        "iba-primary-fixed": "#97f0ff",
        "iba-on-primary-fixed": "#001f24",
        "iba-on-primary-fixed-variant": "#004f57",
        "iba-secondary-fixed": "#cce5ff",
        "iba-on-secondary-fixed": "#001d31",
        "iba-on-secondary-fixed-variant": "#004b73",
        "iba-tertiary-fixed": "#ffdbca",
        "iba-on-tertiary-fixed": "#341100",
        "iba-on-tertiary-fixed-variant": "#783200",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        "iba-body-sm": ["Plus Jakarta Sans"],
        "iba-body-md": ["Plus Jakarta Sans"],
        "iba-body-lg": ["Plus Jakarta Sans"],
        "iba-headline-sm": ["Plus Jakarta Sans"],
        "iba-headline-md": ["Plus Jakarta Sans"],
        "iba-headline-lg": ["Plus Jakarta Sans"],
        "iba-headline-xl": ["Plus Jakarta Sans"],
        "iba-label-badge": ["Plus Jakarta Sans"],
        "iba-label-code": ["JetBrains Mono"],
      },
      fontSize: {
        "iba-body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "iba-body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "iba-body-lg": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "iba-headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "iba-headline-md": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "iba-headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "iba-headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "iba-label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "iba-label-code": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
